# Determines if we search the title (optional). Defaults to true.
matchTitle: true

# Determines if we search the body (optional). Defaults to true.
matchBody: true

# Determines if label matching is case sensitive (optional). Defaults to true.
caseSensitive: false

# Explicit keyword mappings to labels. Form of match:label. Required.
labelMappings:
  "[WIP]": WIP
  "fix:": bugfix
  "add:": feature
  "del:": removal
  "qol:": quality of life
  "balance:": balance
  "sound:": sound
  "image:": image
  "spellcheck:": grammer
  "code:": code improvement
  "refactor:": refactor
  "config:": config edit
  "admin:": administration
  "server": server


